### ISSUE TITLE
Number labels in the world

### ISSUE THREAD

**Issue by schrum2** [schrum2/EvoCraft-SCOPE#3]
Issue #1 is a nice start, but it depends on the user knowing which index corresponds to each evolved shape. It should be possible to figure this out, but it's also easy to get mixed up, since which shape is first/last depends on which side of them you are on. Also, if there are multiple empty spaces in a row, a person might lose count.

Therefore, it would be nice if there was some kind of visual indicator in the world clearly defining which shape is index 0, 1, etc. I'm not sure what form this should take ... surprise me.

**Comment by alejmedinajr** [comment]
Started to work on placing numbers using glow blocks. Right now they are not spaced out appropriately and need to be in sync with their respective shapes being produced (as of now they are off by one shape I believe). I also have not finished them all yet, I have 1 more number to do. I also will change the z coordinates and y coordinates to make the numbers appear above the shapes rather than in a view obstructing place.


![minecraft_nums](https://user-images.githubusercontent.com/100097809/168912320-97647c7c-57c3-4a72-b6d9-ba4f756cf04d.png)

**Comment by alejmedinajr** [comment]
The numbers are now (more) centered above their respective shapes. The numbering system also was changed from 1-10 to 0-9. 


![numbers more centered](https://user-images.githubusercontent.com/100097809/169141489-3e423cda-1b21-44d0-91f7-168af16eb30d.png)

**Comment by alejmedinajr** [comment]
Final picture update as I close this issue.
![numbers mixed with other stuffthat was done](https://user-images.githubusercontent.com/100097809/169143300-a526b131-ade3-483c-8f67-394ab41a5ac2.png)
