### ISSUE TITLE
User controlled blocks: don't show what isn't used

### ISSUE THREAD

**Issue by schrum2** [schrum2/EvoCraft-SCOPE#34]
If a certain type of block is not used at all in a particular shape, then the pedestal that would display that block should displace nothing instead. Perhaps even the emerald block pedestal can be replaced by grass to make the distinction clear. This can help us understand which blocks are actually present. 

This would also indicate if, for example, a block of a different type is hidden inside of the shape that we can see.

**Comment by MuellMark** [comment]
Added in a command line parameter (defaulted to true) that toggles on whether or not to only show blocks that were placed. If it is true, blocks that are placed have emerald underneath them, otherwise, red sandstone is generated where a block would be. This also works with changing blocks in real time
