### ISSUE TITLE
Save image of evolved Neural Network

### ISSUE THREAD

**Issue by schrum2** [schrum2/EvoCraft-SCOPE#53]
Save an image of the evolved neural network at the end of a fitness-based evolutionary run

**Comment by alejmedinajr** [comment]
To use visualization function for this, graphviz needs to be installed, however, Mark is currently not here so waiting off on that.

**Comment by schrum2** [comment]
You can view the generated neural network graphs at https://dreampuf.github.io/GraphvizOnline.
Just paste the text of the file into the site.
![image](https://user-images.githubusercontent.com/8397236/170782186-bf676a3b-8d72-4fe1-95b7-1e9c06c04a92.png)
However, this reveals that the neurons are not being labelled correctly in our code, since you're still using the labels from the pole balancing example this was copied from.

The input neuron labels should be: x, y, z, radius, bias

The output labels depend on other settings. The first is always "presence". The next outputs should be the names of the block types that each output corresponds to. If orientations are being evolved (ask @MuellMark ) then those come next (Each would be "oriented " then the direction, like "oriented north"). If a snake is being evolved, then the directions show up again, either in addition to or instead of the orientation directions. These labels should be "move north", etc. With snakes, the last output is "continue snake"

The graph may not look very good with these long node names. We may need to abbreviate.

**Comment by alejmedinajr** [comment]
Changed the input/output labels. I have included examples of different command line parameters below. Also the actual part that saves the file has been commented out because it causes issues since graph viz is not installed (the file will not be created and saved unless this line is uncommented). 

When only having block type and snake outputs:
![graphviz (3)](https://user-images.githubusercontent.com/100097809/171265319-55976f72-890a-473c-ba59-e743659fc6d1.svg)


When having block type, snake, and orientation outputs: 
![graphviz (2)](https://user-images.githubusercontent.com/100097809/171265325-8298ad1c-4fc6-46b0-9cfb-3deb3ddc9d9f.svg)


When having only block type outputs:
![graphviz (1)](https://user-images.githubusercontent.com/100097809/171265328-52f0ac8e-8f18-48f0-bbbd-d9d2868240e0.svg)


When having block type and orientation outputs:
![graphviz](https://user-images.githubusercontent.com/100097809/171265333-50df0f4c-9a24-41fe-9f7c-bf264f83b8e7.svg)

**Comment by alejmedinajr** [comment]
Made some of the names shorter, and changed to 0 based indexing labels. Also just to clarify, the neural network being produced is at the end of evolution, and is the champion genome's neural network.

New shorter names and zero based indexing labels example:
![graphviz (4)](https://user-images.githubusercontent.com/100097809/171272244-39f8de7d-ff30-4303-ae0d-e86f5053d1e7.svg)
